[general]
live_config_reload = true
import = [
  "~/.config/alacritty/dark-orchid.toml"
]
ipc_socket = false

[env]
TERMINAL_EMULATION = "true"
# TERM = "xterm-256color"

[window]
padding = { x = 8, y = 8 }
decorations = "Buttonless"
opacity = 0.8
blur = true
dynamic_title = true

[cursor]
style = { shape = "Block", blinking = "Never" }
vi_mode_style = { shape = "Block", blinking = "Never" }
unfocused_hollow = false

[mouse]
hide_when_typing = true

[font]
normal = { family = "Blex Mono Nerd Font" }
size = 13
builtin_box_drawing = false

[keyboard]
bindings = [
  { key = "Return", mods = "Alt", action = "SpawnNewInstance" }
]
