'$schema' = 'https://starship.rs/config-schema.json'

palette = 'custom'

add_newline = true

format = """
$directory\
$git_branch\
$git_status\
$character\
"""

[directory]
format = '[$path](fg:purple) '
truncate_to_repo = true
truncation_length = 6
read_only = ''
read_only_style = ''

[git_branch]
format = '([\($branch\)](fg:purple) )'

[git_status]
format = '([\[$all_status\]](fg:purple) )'
conflicted = ''
ahead = '⇡'
behind = '⇣'
diverged = '⇕'
untracked = '?'
stashed = '$'
modified = '!'
staged = '+'
renamed = '»'
deleted = ''

[character]
format = '[~>](fg:purple) '

[palettes.custom]
purple = '#7300ff'
white = '#ffffff'
